### ISSUE TITLE
No text appears

### ISSUE THREAD

**Issue by jepler** [lxi-tools/lxi-tools.snapcraft#1]
Similar to the behavior described at https://github.com/keepassxreboot/keepassxc/issues/1271 on Debian Stretch lxi-gui gets no fonts at all unless you run a command similar to 
```
cd $HOME/snap/lxi-tools/current/.local/share
ln -s /snap/lxi-tools/current/usr/share/fonts .
```

![image](https://user-images.githubusercontent.com/1517291/42163715-2fb2bb0e-7dc9-11e8-80ed-4acd1a1574d1.png)

**Comment by jepler** [comment]
Steps to reproduce:
Boot the Debian "stretch" x86_64 live cd image. 

You can do it in qemu:
`qemu-system-x86_64 -enable-kvm -m 1024 -cdrom debian-live-9.0.1-amd64-xfce.iso`

Once booted to the virtualized desktop, open a terminal and
```
sudo apt update
sudo apt install snapd
sudo service snapd start
sudo snapd install 
snap run lxi-tools.lxi-gui
```

I tested with the older 9.0.1 image with the xfce desktop environment.  However, the problem also occurs on an up to date Debian 9.4.  I did not check whether other DEs are affected.

The problem does *NOT* affect the version from the 'edge' channel, only 1.20 (940).  Given that there is a workaround for the stable version, and the edge version is not affected, I will understand if the maintainers prefer to close this issue up.  Thanks for your time! I am looking forward to using lxi-tools.

**Comment by lundmar** [comment]
Thanks for reporting the bug.

I've tried explicitly adding the font package dependencies to the snapcraft.yaml but it didn't make any difference.

It works fine on Ubuntu etc. - perhaps it is caused by some missing or broken configuration of snapd for Debian.

I've reported the issue in the snapcraft forum:
https://forum.snapcraft.io/t/font-issue-no-text-appears-in-qt-application/6208

**Comment by lundmar** [comment]
@jepler Could you please check for the file ~/snap/$snapname/current/.config/fontsconfig/fonts.conf as described here: https://forum.snapcraft.io/t/font-issue-no-text-appears-in-qt-application/6208/2 ?

Thanks.

**Comment by jepler** [comment]
With the affected "940" revision of lxi-tools, the content of the file is:
```
jepler@babs:~/snap/lxi-tools/current/.config/fontconfig$ cat fonts.conf
<fontconfig>
  <dir>/home/jepler/.fonts</dir>
  <dir>/snap/lxi-tools/940/usr/share/fonts</dir>
  <cachedir prefix="xdg">fontconfig</cachedir>
  <cachedir>/home/jepler/.cache/fontconfig</cachedir>
</fontconfig>
```

With the unaffected "967" revision of lxi-tools, the content of the file is:
```
jepler@babs:~/snap/lxi-tools/current/.config/fontconfig$ cat fonts.conf
<fontconfig>
  <dir>/home/jepler/.fonts</dir>
  <dir>/snap/lxi-tools/967/usr/share/fonts</dir>
  <include ignore_missing="yes">conf.d</include>
  <cachedir prefix="xdg">fontconfig</cachedir>
  <cachedir>/home/jepler/.cache/fontconfig</cachedir>
</fontconfig>
```

The file differences are:
```
--- 940/.config/fontconfig/fonts.conf	2018-07-07 22:21:12.939587499 -0500
+++ 967/.config/fontconfig/fonts.conf	2018-07-07 22:22:38.103978245 -0500
@@ -1,6 +1,7 @@
 <fontconfig>
   <dir>/home/jepler/.fonts</dir>
-  <dir>/snap/lxi-tools/940/usr/share/fonts</dir>
+  <dir>/snap/lxi-tools/967/usr/share/fonts</dir>
+  <include ignore_missing="yes">conf.d</include>
   <cachedir prefix="xdg">fontconfig</cachedir>
   <cachedir>/home/jepler/.cache/fontconfig</cachedir>
 </fontconfig>
```

However, manually removing the `<include>` directive from 967 does not make it regress to 940 behavior, so that's not a cause or solution.  In fact, just copying the `fonts.conf` content from 940 into 967 doesn't make 967 manifest the problem; 967 successfully uses font content from the 940 snap according to `snap run --strace`.

.. in fact, 940 never accesses `/home/jepler/snap/lxi-tools/940/.config/fontconfig/fonts.conf` at all according to strace.

**Comment by jepler** [comment]
Maybe it's this difference in bin/desktop-launch?
```
--- 940/bin/desktop-launch      2018-05-05 09:30:05.000000000 -0500
+++ 967/bin/desktop-launch      2018-07-02 13:00:16.000000000 -0500
...
-export FONTCONFIG_FILE=$RUNTIME/etc/fonts/fonts.conf
+export FONTCONFIG_FILE=$XDG_CONFIG_HOME/fontconfig/fonts.conf
```

Related change, though it just refers to fonts becoming ugly, not disappearing: https://github.com/ubuntu/snapcraft-desktop-helpers/pull/115

I don't know the logistics of reissuing 1.20 with refreshed `snapcraft-desktop-helpers` vs the timeline on when 1.21 will become stable, but again it's OK by me to close this up since there's a workaround and the next release will fix it.

**Comment by lundmar** [comment]
Thank you very much for investigating :+1: 

It's difficult to pinpoint exactly why it suddenly started working. I think it is one of those things which might simply have been fixed by recent versions of snapcraft/snapd. I guess it's kind of a moving target still.

To fix the issue I've pushed a new stable release. Let me know if it fixes the issue for you on the stable channel.

On a related note, I hope there will soon be a new version of snap core based on Ubuntu 18.04 LTS which will include a more recent QT version to make the UI look even better. All snaps currently run using snap core image based on Ubuntu 16.04 LTS which makes the graphics details look a bit off, including fonts I think.

**Comment by jepler** [comment]
the GUI looks fine with revsion 978.

```name:      lxi-tools
summary:   Open source LXI tools
publisher: lundmar
license:   unknown
description: |
  Lxi-tools is a collection of open source software tools that enables control of LXI compatible
  instruments such as modern oscilloscopes, power supplies, spectrum analyzers etc.
commands:
  - lxi-tools.lxi
  - lxi-tools.lxi-gui
snap-id:      yha3V4dqfwJwpjSWgMFEMViAlQ2iMdL7
tracking:     stable
refresh-date: yesterday at 07:15 CDT
channels:                     
  stable:    1.21 (978) 147MB -
  candidate: ↑                
  beta:      ↑                
  edge:      1.21 (978) 147MB -
installed:   1.21 (978) 147MB -
```
